version: '3'
services:
  mongodb:
    image: mongo:4.0
    ports:
      - "57017:27017"
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=rootpassword"
  mysql:
    image: mysql:5.7
    ports:
      - "53306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=rootpassword"
      - "MYSQL_DATABASE=demo"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=adminpassword"
    